spring.application.name=backend
server.port=9091

spring.datasource.url=jdbc:postgresql://localhost:5432/ADHDStudyAppDb
spring.datasource.username=postgres
spring.datasource.password=1234567890

# JPA and Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jackson.serialization.write-dates-as-timestamps=false

jwt.secret=c2VjdXJlLXNlY3JldC1rZXktMTIzNDU2Nzg5MDEyMzQ1Ng==
